//
// Generated file, do not edit! Created by nedtool 5.7 from veins/base/utils/Coord.msg.
//

#ifndef __VEINS_COORD_M_H
#define __VEINS_COORD_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

} // namespace veins

#include "veins/common_m.h" // import veins.common

// cplusplus {{
#include "veins/base/utils/Coord.h"
// }}


namespace veins {

} // namespace veins

#endif // ifndef __VEINS_COORD_M_H

